### ISSUE TITLE
Cann't communicate via hostname in swarm cluster

### ISSUE THREAD

**Issue by zhuqinghua** [YevhenPavliuchek/ha-redis-docker-swarm-kubernetes#1]
Can you tell me which version of docker is used? In my swarm cluster, the containers cannot communicate with each other by hostname.Thanks

**Comment by YevhenPavliuchek** [comment]
It was tested about 4 months ago with the latest version available at that time, the one where writing 'version:' in Docker Compose just became deprecated

with such overlay network:

docker network create -d overlay --attachable test

docker compose:
```
networks:
  test:
    external: true

services:
  redis:
......
    networks:
      - test

  redis-sentinel:
......
    networks:
      - test
    
```
